### ISSUE TITLE
Gradle Sync Issue

### ISSUE THREAD

**Issue by walau1997** [udacity/ud839_Miwok#134] opened 2019-01-17 13:08 UTC
How can I solve these issues?

![111](https://user-images.githubusercontent.com/46783365/51320830-07d30100-1a9c-11e9-8609-0b0b3dc8bf4d.JPG)

**Comment by Kvaibhav01** [comment] 2019-01-17 14:06
These are all warnings which won't affect the running of your app but are recommended to do. Here's how you solve them:

For issue 1 and 2: In your app-level _build.gradle_ file replace `compile` and `testCompile` with `implementation` and `testImplementation` respectively.

For issue 3: Update your `buildToolsVersion` in the same file. Something like `27.0.3`. Sync and rebuild your project.

Check [this similar question](https://stackoverflow.com/questions/47146694/the-specified-android-sdk-build-tools-version-26-0-0-is-ignored) in Stackoverflow.

**Comment by walau1997** [comment] 2019-01-18 12:36
Hi there,I have found a new issue and this is it
 
![112](https://user-images.githubusercontent.com/46783365/51387358-ba6c9780-1b60-11e9-94c0-47c2c453c777.JPG)

**Comment by Kvaibhav01** [comment] 2019-01-18 17:43
Android Studio will tell you the fix. Hover over the `23` and hit <kbd>alt+tab</kbd> see the suggestion, it's most likely that the targetSdkVersion is lower or higher.

**Comment by kisyular** [comment] 2019-01-30 01:18
`buildscript {
    repositories {
        mavenCentral()
        google() // For Gradle 4.0+
        maven { url 'https://maven.google.com' } // For Gradle < 4.0
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
    }
}
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27

    defaultConfig {
        applicationId "com.example.android.miwok"
        minSdkVersion 15
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.1'
}

repositories {
    google()
}
`

**Comment by jiffner** [comment] 2019-02-07 20:58
> Android Studio will tell you the fix. Hover over the `23` and hit alt+tab see the suggestion, it's most likely that the targetSdkVersion is lower or higher.

So how do I change the SDK Version?

**Comment by Kvaibhav01** [comment] 2019-02-09 13:56
> Hi there,I have found a new issue and this is it
> 
> ![112](https://user-images.githubusercontent.com/46783365/51387358-ba6c9780-1b60-11e9-94c0-47c2c453c777.JPG)

@jiffner, See this image, all you need to do is increment or decrement the `targetSdkVersion`. Android Studio will help you in this.

**Comment by asem0525** [comment] 2019-03-28 13:15
this helped me:

Most likely you do not have the Google repository in your project's build.gradle file. Add google() in BOTH locations as shown below:

buildscript {

    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

from stackoverflow

**Comment by navneethosmane1499** [comment] 2019-04-30 13:07
I am having trouble with MainActivity.Java also. I fixed the gradle but the error is coming in java `part.
![Screenshot from 2019-04-30 18-33-54](https://user-images.githubusercontent.com/49156117/56963637-0a52f580-6b77-11e9-9cf0-a08e50bffe30.png)
`

**Comment by Kvaibhav01** [comment] 2019-05-01 08:52
@lonewolf1499 you need to sync the Gradle with the changes made. If the error still exists, hover over the error and click on the bulb icon where Android Studio will suggest the necessary code changes. Most probably, the issue is of importing the classes.

**Comment by navneethosmane1499** [comment] 2019-05-02 02:02
should compileSDKversion and targetSDKversion same version ?

**Comment by navneethosmane1499** [comment] 2019-05-02 02:31
![Screenshot from 2019-05-02 07-59-05](https://user-images.githubusercontent.com/49156117/57054137-4342b580-6cb0-11e9-8596-a63927cceea6.png)

Now I am getting only this error. And I tried with different versions it's not working.

**Comment by Kvaibhav01** [comment] 2019-05-03 07:47
In your project-level _build.gradle_ file, add the code line given below:

```
allprojects {
        repositories {
            jcenter()
            google() // THIS ONE
        }
    }
```
After this, sync and clean the project.

**Comment by imabhisht** [comment] 2019-06-05 13:14
How can i solve this issue!!
[ud839_Miwok]
![#@323](https://user-images.githubusercontent.com/51349137/58958718-29215900-87c1-11e9-8a18-3bafea6eef10.PNG)

build.gradle is:-
![2323](https://user-images.githubusercontent.com/51349137/58958797-4eae6280-87c1-11e9-8e8a-0d1d79e23a6f.PNG)
![sdsdsdsaAA](https://user-images.githubusercontent.com/51349137/58958815-5837ca80-87c1-11e9-8801-3755661a8f73.PNG)

Plz help. Im new on these.....

**Comment by Kvaibhav01** [comment] 2019-06-05 14:28
@abhishtchouhan, the error will be fixed once you add the Google Maven repository and sync the project as suggested in the error log. Just click on that link and you should be good to go!

**Comment by navneethosmane1499** [comment] 2019-06-05 16:42
> @lonewolf1499 you need to sync the Gradle with the changes made. If the error still exists, hover over the error and click on the bulb icon where Android Studio will suggest the necessary code changes. Most probably, the issue is of importing the classes.

Thanks for the suggestion. I already solved the problem by copying the repository in github directly to android studio.

**Comment by SudKul** [comment] 2022-02-14 11:08
We have updated all branches to use Gradle 7.x, mavenCentral() repository, SDK API level 31, and AndroidX dependencies.

**Closed as completed by SudKul** 2022-02-14 11:08 UTC
