### ISSUE TITLE
cant run apps, Look in Screenshot.

### ISSUE THREAD

**Issue by rahulzx** [udacity/ud839_Miwok#45] opened 2017-09-24 11:50 UTC
![screenshot 21](https://user-images.githubusercontent.com/26010295/30782281-92b03f6a-a14c-11e7-8c56-d62125af7d3c.png)

**Comment by Kvaibhav01** [comment] 2017-09-24 14:44
Hey there! Your code looks fine. You need to reopen the project. The issue is of Gradle sync here. Perform these steps:

1. Reopen the project from scratch.
2. Fix the Gradle sync and SDK warnings that you see in the Messages tab.

This is what I did and the app runs perfectly fine! See the screenshot below:
![ss](https://user-images.githubusercontent.com/11731837/30783697-f294da54-a164-11e7-82d8-bff891e692dc.PNG)

**Comment by rahulzx** [comment] 2017-09-25 11:02
i fix it a new way, thanku for helping...

**Comment by Kvaibhav01** [comment] 2017-09-25 14:21
How? Can you share?

**Comment by Kvaibhav01** [comment] 2017-10-02 14:09
@rahulzx, please close the issue!

**Comment by BUKJACK** [comment] 2018-03-10 17:24
You need to import, "AppCompatActivity.java".

Add, the following import statement, and it should work fine,

import android.support.v7.app.AppCompatActivity;

**Comment by SudKul** [comment] 2022-02-14 11:48
We have updated all branches to use Gradle 7.x, SDK API level 31, and AndroidX dependencies. 


Should you (or any learner) need help on individual issues, we recommend using the https://knowledge.udacity.com/ platform to discuss with our experienced mentors.

**Closed as completed by SudKul** 2022-02-14 11:48 UTC
